DATA CLEANING

In [30]:
import pandas as pd
import numpy as np

In [31]:
data={'A':[10,20,'?',40,50],
      'B':[np.nan,2000,3000,11000,'?']
}

In [32]:
df=pd.DataFrame(data)

In [33]:
df

    A      B
0  10    NaN
1  20   2000
2   ?   3000
3  40  11000
4  50      ?

In [34]:
df.replace('?',np.nan,inplace=True)

C:\Users\Samarth\AppData\Local\Temp\ipykernel_9512\1615161097.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('?',np.nan,inplace=True)

In [35]:
df

      A        B
0  10.0      NaN
1  20.0   2000.0
2   NaN   3000.0
3  40.0  11000.0
4  50.0      NaN

In [36]:
df.isnull()

       A      B
0  False   True
1  False  False
2   True  False
3  False  False
4  False   True

In [37]:
df2=df.fillna(df.mean())

In [38]:
df2

      A             B
0  10.0   5333.333333
1  20.0   2000.000000
2  30.0   3000.000000
3  40.0  11000.000000
4  50.0   5333.333333

In [39]:
df

      A        B
0  10.0      NaN
1  20.0   2000.0
2   NaN   3000.0
3  40.0  11000.0
4  50.0      NaN

In [40]:
df3=df.fillna(method='bfill')

C:\Users\Samarth\AppData\Local\Temp\ipykernel_9512\348519034.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3=df.fillna(method='bfill')

In [41]:
df3

      A        B
0  10.0   2000.0
1  20.0   2000.0
2  40.0   3000.0
3  40.0  11000.0
4  50.0      NaN

In [42]:
df4=df.interpolate(method='linear')

In [43]:
df2.nunique()

A    5
B    4
dtype: int64

In [44]:
df2.describe()

               A             B
count   5.000000      5.000000
mean   30.000000   5333.333333
std    15.811388   3488.074923
min    10.000000   2000.000000
25%    20.000000   3000.000000
50%    30.000000   5333.333333
75%    40.000000   5333.333333
max    50.000000  11000.000000

In [45]:
df2

      A             B
0  10.0   5333.333333
1  20.0   2000.000000
2  30.0   3000.000000
3  40.0  11000.000000
4  50.0   5333.333333

In [46]:
df2['C']=['a','b','c','d','e']

In [47]:
df2['A'].quantile(0.25)

np.float64(20.0)

In [48]:
df2['B'].quantile(0.75)

np.float64(5333.333333333333)

In [49]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      float64
 1   B       5 non-null      float64
 2   C       5 non-null      object
dtypes: float64(2), object(1)
memory usage: 248.0+ bytes

In [50]:
def replaceNoisy(col):
  q1=col.quantile(0.25)
  q3=col.quantile(0.75)
  iqr=q3-q1
  lower=q1-(1.5*iqr)
  upper=q3*(1.5*iqr)
  median=col.median()
  return col.apply(lambda x: median if(x<=lower) |(x>=upper) else x)
df2[df2.select_dtypes(include='number').columns]=df2.select_dtypes(include='number').apply(replaceNoisy)

In [51]:
df2

      A             B  C
0  10.0   5333.333333  a
1  20.0   2000.000000  b
2  30.0   3000.000000  c
3  40.0  11000.000000  d
4  50.0   5333.333333  e

In [52]:
data={'Year':[1,2,3,4,5,6],'Price':[100,200,np.nan,400,500,np.nan]}
df=pd.DataFrame(data)

In [53]:
df

   Year  Price
0     1  100.0
1     2  200.0
2     3    NaN
3     4  400.0
4     5  500.0
5     6    NaN

In [54]:
df.interpolate(method='linear',inplace=True)

In [55]:
df

   Year  Price
0     1  100.0
1     2  200.0
2     3  300.0
3     4  400.0
4     5  500.0
5     6  500.0