EMPLOYEE DATASET

In [2]:
import pandas as pd

In [3]:
data={
  'Id':[101,102,103,104,105,106,107,108],
  'Name':['Alice','Bob','Charlie','David','Emma','Frank','Grace','Helen'],
  'Department':['HR','IT','IT','Finance','HR','IT','Finance','HR'],
  'Salary':[60000,75000,80000,72000,65000,78000,70000,62000],
  'ExperienceYears':[5,7,6,8,4,9,6,3]
}
df=pd.DataFrame(data)

In [4]:
df.to_csv('Employee.csv',index=False)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               8 non-null      int64
 1   Name             8 non-null      object
 2   Department       8 non-null      object
 3   Salary           8 non-null      int64
 4   ExperienceYears  8 non-null      int64
dtypes: int64(3), object(2)
memory usage: 448.0+ bytes

In [6]:
df.describe()

              Id       Salary  ExperienceYears
count    8.00000      8.00000             8.00
mean   104.50000  70250.00000             6.00
std      2.44949   7382.41153             2.00
min    101.00000  60000.00000             3.00
25%    102.75000  64250.00000             4.75
50%    104.50000  71000.00000             6.00
75%    106.25000  75750.00000             7.25
max    108.00000  80000.00000             9.00

In [ ]:
df['Department'].nunique()

Department
HR         3
IT         3
Finance    2
Name: count, dtype: int64

In [8]:
print('Employee with max salary: ')
maxSalary=df['Salary'].max()
# df[df['Salary']==maxSalary][['Name','Salary']] ----alternate method
df.loc[df['Salary']==maxSalary,['Name','Salary']]

Employee with max salary:

      Name  Salary
2  Charlie   80000

In [9]:
print("Employees working in IT department: ")
df[(df['Department']=='IT') & (df['Salary']<80000)][['Name','Salary','Department']]

Employees working in IT department:

    Name  Salary Department
1    Bob   75000         IT
5  Frank   78000         IT

In [18]:
print('Department wise max salary')
df1=df.groupby('Department')['Salary'].max().reset_index()
df1

Department wise max salary

  Department  Salary
0    Finance   72000
1         HR   65000
2         IT   80000

In [11]:
print("Department wise details: ")
df1=df.groupby('Department').agg({'Salary':['min','max','mean'],'ExperienceYears':['sum']}).reset_index()
df1

Department wise details:

  Department Salary                      ExperienceYears
                min    max          mean             sum
0    Finance  70000  72000  71000.000000              14
1         HR  60000  65000  62333.333333              12
2         IT  75000  80000  77666.666667              22

In [12]:
df1=df.groupby(['Department','ExperienceYears'])['Salary'].mean().reset_index()
df1

  Department  ExperienceYears   Salary
0    Finance                6  70000.0
1    Finance                8  72000.0
2         HR                3  62000.0
3         HR                4  65000.0
4         HR                5  60000.0
5         IT                6  80000.0
6         IT                7  75000.0
7         IT                9  78000.0

In [19]:
print('Department wise employee count: ')
# df1=df.groupby('Department')['Id'].count().reset_index(name='Count')
# df1
df.value_counts('Department').reset_index(name='No of employees')

Department wise employee count:

  Department  No of employees
0         HR                3
1         IT                3
2    Finance                2

In [14]:
df1=df.sort_values(by=['Salary','ExperienceYears'],ascending=[False,True])
df1

    Id     Name Department  Salary  ExperienceYears
2  103  Charlie         IT   80000                6
5  106    Frank         IT   78000                9
1  102      Bob         IT   75000                7
3  104    David    Finance   72000                8
6  107    Grace    Finance   70000                6
4  105     Emma         HR   65000                4
7  108    Helen         HR   62000                3
0  101    Alice         HR   60000                5

In [15]:
df['Tax']=df['Salary']*0.30
df

    Id     Name Department  Salary  ExperienceYears      Tax
0  101    Alice         HR   60000                5  18000.0
1  102      Bob         IT   75000                7  22500.0
2  103  Charlie         IT   80000                6  24000.0
3  104    David    Finance   72000                8  21600.0
4  105     Emma         HR   65000                4  19500.0
5  106    Frank         IT   78000                9  23400.0
6  107    Grace    Finance   70000                6  21000.0
7  108    Helen         HR   62000                3  18600.0

In [16]:
df['Tax_Category']=df['Tax'].apply(lambda x: 'High' if x>20000 else 'Low')
df

    Id     Name Department  Salary  ExperienceYears      Tax Tax_Category
0  101    Alice         HR   60000                5  18000.0          Low
1  102      Bob         IT   75000                7  22500.0         High
2  103  Charlie         IT   80000                6  24000.0         High
3  104    David    Finance   72000                8  21600.0         High
4  105     Emma         HR   65000                4  19500.0          Low
5  106    Frank         IT   78000                9  23400.0         High
6  107    Grace    Finance   70000                6  21000.0         High
7  108    Helen         HR   62000                3  18600.0          Low