In [11]:
import pandas as pd

In [12]:
data={'Col1':['a','b','a','b','c','a','b','c'],'Col2':[101,102,103,101,102,103,104,103],'Col3':[10,20,10,20,30,20,10,50]}
df=pd.DataFrame(data)

In [13]:
df

  Col1  Col2  Col3
0    a   101    10
1    b   102    20
2    a   103    10
3    b   101    20
4    c   102    30
5    a   103    20
6    b   104    10
7    c   103    50

In [20]:
df=df.drop(columns='Col1')

In [21]:
df

   Col2  Col3
0   101    10
1   102    20
2   103    10
3   101    20
4   102    30
5   103    20
6   104    10
7   103    50

In [18]:
df1=df.groupby(['Col1','Col2']).value_counts(['Col3']).reset_index(name='Total')

In [19]:
df1

  Col1  Col2  Col3  Total
0    a   101    10      1
1    a   103    10      1
2    a   103    20      1
3    b   101    20      1
4    b   102    20      1
5    b   104    10      1
6    c   102    30      1
7    c   103    50      1

In [16]:
df2=df.groupby('Col1')['Col2'].count().reset_index(name='Total')

In [17]:
df2

  Col1  Total
0    a      3
1    b      3
2    c      2

In [22]:
df.describe()

            Col2       Col3
count    8.00000   8.000000
mean   102.37500  21.250000
std      1.06066  13.562027
min    101.00000  10.000000
25%    101.75000  10.000000
50%    102.50000  20.000000
75%    103.00000  22.500000
max    104.00000  50.000000