MISSING VALUES

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.DataFrame({'a':[85,90,78]})

print(df['a'].mean())

84.33333333333333

In [5]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, np.nan, 30, 45, np.nan],
    'City': ['New York', 'Los Angeles', np.nan, 'Chicago', 'New York'],
    'Salary': [70000, 80000, np.nan, 120000, 95000]
}
df=pd.DataFrame(data)
df.to_csv('Sample.csv',index=False)

In [6]:
df

      Name   Age         City    Salary
0    Alice  25.0     New York   70000.0
1      Bob   NaN  Los Angeles   80000.0
2  Charlie  30.0          NaN       NaN
3    David  45.0      Chicago  120000.0
4      Eve   NaN     New York   95000.0

In [7]:
df.isna()

    Name    Age   City  Salary
0  False  False  False   False
1  False   True  False   False
2  False  False   True    True
3  False  False  False   False
4  False   True  False   False

In [8]:
df.isnull().sum()

Name      0
Age       2
City      1
Salary    1
dtype: int64

In [9]:
# maxCity=df.value_counts('City').idxmax()
# df2=df.fillna({'Age':df['Age'].mean(),'City':maxCity,'Salary':df['Salary'].mean()})
# use of mode
df2=df.fillna({'Age':df['Age'].mean(),'City':df['City'].mode()[0],'Salary':df['Salary'].mean()})
df2

      Name        Age         City    Salary
0    Alice  25.000000     New York   70000.0
1      Bob  33.333333  Los Angeles   80000.0
2  Charlie  30.000000     New York   91250.0
3    David  45.000000      Chicago  120000.0
4      Eve  33.333333     New York   95000.0

In [10]:
df

      Name   Age         City    Salary
0    Alice  25.0     New York   70000.0
1      Bob   NaN  Los Angeles   80000.0
2  Charlie  30.0          NaN       NaN
3    David  45.0      Chicago  120000.0
4      Eve   NaN     New York   95000.0

In [11]:
df2=df.fillna(df.mean(numeric_only=True))

In [12]:
df2

      Name        Age         City    Salary
0    Alice  25.000000     New York   70000.0
1      Bob  33.333333  Los Angeles   80000.0
2  Charlie  30.000000          NaN   91250.0
3    David  45.000000      Chicago  120000.0
4      Eve  33.333333     New York   95000.0

In [17]:
data={'A':[10,20,10,30],
      'B':['a','b','b','a'],
      'C':[100,200,300,400]}

In [18]:
d=pd.DataFrame(data)

In [15]:
d

    A  B
0  10  a
1  20  b
2  10  b
3  30  a

In [16]:
d1=d.groupby('B').value_counts('A').reset_index()
d1

   B   A  count
0  a  10      1
1  a  30      1
2  b  10      1
3  b  20      1

In [21]:
d['avg']=d[['A','C']].mean(axis=1)

In [22]:
d

    A  B    C    avg
0  10  a  100   55.0
1  20  b  200  110.0
2  10  b  300  155.0
3  30  a  400  215.0