# Data Visualization
# BTech Computer Science Stream , January 2025
# Week 4 - Pandas Demonstration Notebook
# Sujithra,  Reg Number , Date: 06/01/2025

In [ ]:
# Reading data is also called as data loading
# The term parsing is also sometimes used to describe loading text data and interpreting it as tables and different data types. 
# The focus is on data input and output using pandas

In [1]:
import numpy as np
import pandas as pd

Use notepad and create a .csv file called 'ex1.csv' with the following contents
a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [3]:
# Since this is comma-delimited, we can then use pandas.read_csv to read it into a DataFrame:
df1 = pd.read_csv("ex1.csv")
df1

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Create another file 'ex2.csv' with the following contents and no header row
1,2,3,4,first
5,6,7,8,second
9,10,11,12,third

In [6]:
#df2=pd.read_csv("ex2.csv", header=None)
df2=pd.read_csv("ex2.csv", names=["a", "b", "c", "d", "message"])
df2

   a   b   c   d message
0  1   2   3   4   first
1  5   6   7   8  second
2  9  10  11  12   third

Missing data is usually either not present (empty string) or marked by some sentinel (placeholder) value. 
By default, pandas uses a set of commonly occurring sentinels, such as NA and NULL:

Create another file 'ex3.csv' with the following contents
something,a,b,c,d,message
one,1,2,3,4,
two,5,6,,8,world
three,9,10,11,12,foo

In [8]:
# The na_values option accepts a sequence of strings to add to the default list of strings recognized as missing:
df3 = pd.read_csv("ex3.csv")
#df3
#pd.isna(df3)
df3.isna()

   something       a      b      c      d  message
0       False  False  False  False  False     True
1       False  False  False   True  False    False
2       False  False  False  False  False    False

Create an excel file called StdMrks.xls with two sheets. 1 sheet contains roll number, name of 5 students with their marks in 5 quizzes (out of 10). The other sheet contains marks obtained in two exams (out of 100 each ) for the same student.

In [11]:
# Reading the file , sheet by sheet
xlsx = pd.ExcelFile("StudMrks.xlsx")

In [12]:
# This object can show you the list of available sheet names in the file and how to parse them 
xlsx.sheet_names

['Quiz', 'Exam']

In [47]:
df_mrks1=xlsx.parse(sheet_name="Quiz")
df_mrks2=xlsx.parse(sheet_name="Exam", usecols=["E1", "E2"])

In [49]:
df_mrks1

   RollNumber Name  Q1  Q2  Q3  Q4  Q5
0           1  Ram   5   8   9   6   7
1           2  Sam   8   8   6   7   7
2           3  Tam   7   8   9   5   6
3           4  Ham   5   7   6   7   6
4           5  Pam   6   8   6   8   7

In [50]:
df_mrks2

   E1  E2
0  65  58
1  67  68
2  87  85
3  84  76
4  86  76

In [24]:
# This Excel table has an roll number column, so we can indicate that with the index_col argument:
df_mrks3=xlsx.parse(sheet_name="Sheet1", index_col=0)

In [25]:
df_mrks3

             Name  Quiz 1  Quiz 2  Quiz 3
Roll Number
1             Ram       3       7       7
2            Sita       4       8       5
3             Abc       6       4       3
4            Amit       3       2       2
5            Neel       7       5       2

In [52]:
combined_df = pd.concat([df_mrks1, df_mrks2], axis=1)
combined_df

   RollNumber Name  Q1  Q2  Q3  Q4  Q5  E1  E2
0           1  Ram   5   8   9   6   7  65  58
1           2  Sam   8   8   6   7   7  67  68
2           3  Tam   7   8   9   5   6  87  85
3           4  Ham   5   7   6   7   6  84  76
4           5  Pam   6   8   6   8   7  86  76

In [45]:
# f you are reading multiple sheets in a file, then can also simply pass the filename to pandas.read_excel:
frame1 = pd.read_excel("StudMrks.xlsx", sheet_name="Quiz")
frame2 =  pd.read_excel("StudMrks.xlsx", sheet_name="Exam",usecols=["E1", "E2"])
#frame1
frame2
# Combine both DataFrames side by side (column-wise merge)
combined_df = pd.concat([frame1, frame2], axis=1)

# Save the combined data to a new Excel file (optional)
combined_df.to_excel("combined_dataset.xlsx", index=False)

# Display the first few rows
print(combined_df.head())

   RollNumber Name  Q1  Q2  Q3  Q4  Q5  E1  E2
0           1  Ram   5   8   9   6   7  65  58
1           2  Sam   8   8   6   7   7  67  68
2           3  Tam   7   8   9   5   6  87  85
3           4  Ham   5   7   6   7   6  84  76
4           5  Pam   6   8   6   8   7  86  76

In [17]:
# To write pandas data to Excel format, you must first create an ExcelWriter, then write data to it using the pandas object's to_excel method:
frame1.to_excel("Mrks2.xlsx")

In [18]:
frame1

   RollNumber Name  Q1  Q2  Q3  Q4  Q5
0           1  Ram   5   8   9   6   7
1           2  Sam   8   8   6   7   7
2           3  Tam   7   8   9   5   6
3           4  Ham   5   7   6   7   6
4           5  Pam   6   8   6   8   7

In [39]:
import pandas as pd

# Load the Excel file
file_path = "SMnew.xlsx"  # Replace with the actual file path

# Specify the sheets and the columns to extract
sheets_to_combine = { "Quiz", "Exam": ["E1", "E2"]  # Columns C and D from Sheet2
}

# Read only the selected columns from the specified sheets
sheet_dfs = {sheet: pd.read_excel(file_path, sheet_name="Quiz", usecols=columns) 
             for sheet, columns in sheets_to_combine.items()}

# Merge both DataFrames
combined_df = pd.concat(sheet_dfs.values(), axis=1)  # Merging side by side

# Save the new dataset to a new Excel file (optional)
combined_df.to_excel("combined_selected_columns.xlsx", index=False)

# Display the first few rows
print(combined_df.head())

SyntaxError: invalid syntax (3263309780.py, line 7)

In [42]:
import pandas as pd

# Load the Excel file
file_path = "StudMrks.xlsx"  # Replace with your actual file path

# Read ALL columns from "Quiz" sheet (Sheet1)
df1 = pd.read_excel(file_path, sheet_name="Quiz")  # Reads all columns

# Read ONLY specific columns from "Exam" sheet (Sheet2)
df2 = pd.read_excel(file_path, sheet_name="Exam", usecols=["E1", "E2"])  # Replace with actual column names

# Combine both DataFrames side by side (column-wise merge)
combined_df = pd.concat([df1, df2], axis=1)

# Save the combined data to a new Excel file (optional)
combined_df.to_excel("combined_dataset.xlsx", index=False)

# Display the first few rows
print(combined_df.head())

   RollNumber Name  Q1  Q2  Q3  Q4  Q5  E1  E2
0           1  Ram   5   8   9   6   7  65  58
1           2  Sam   8   8   6   7   7  67  68
2           3  Tam   7   8   9   5   6  87  85
3           4  Ham   5   7   6   7   6  84  76
4           5  Pam   6   8   6   8   7  86  76

In [31]:
import pandas as pd

# Load the Excel file
file_path = "SMnew.xlsx"  # Replace with your actual file path

# Read specific columns from "Quiz" sheet
frame1 = pd.read_excel(file_path, sheet_name="Quiz", usecols=["ColumnA", "ColumnB", "ColumnC"])  # Replace with actual column names

# Read specific columns from another sheet, e.g., "Exam"
frame2 = pd.read_excel(file_path, sheet_name="Exam", usecols=["ColumnX", "ColumnY"])  # Replace with actual column names

# Combine both DataFrames side by side (column-wise merge)
combined_df = pd.concat([frame1, frame2], axis=1)

# Save the combined data to a new Excel file (optional)
combined_df.to_excel("combined_dataset.xlsx", index=False)

# Display the first few rows
print(combined_df.head())

ValueError: Usecols do not match columns, columns expected but not found: ['ColumnB', 'ColumnC', 'ColumnA'] (sheet: Quiz)