In [57]:
import pandas as pd

In [58]:
data={'A':[1,2,3,10000,10],'B':['a','b','c','c','e']}

In [59]:
df=pd.DataFrame(data)

In [60]:
df

       A  B
0      1  a
1      2  b
2      3  c
3  10000  c
4     10  e

In [61]:
df['A'].median()

np.float64(3.0)

In [62]:
df.describe()

                  A
count      5.000000
mean    2003.200000
std     4470.348499
min        1.000000
25%        2.000000
50%        3.000000
75%       10.000000
max    10000.000000

In [63]:
def replaceNoisy(col):
  q1=col.quantile(0.25)
  q3=col.quantile(0.75)
  iqr=q3-q1
  lower=q1-(1.5*iqr)
  upper=q3+(1.5*iqr)
  m=col.median()
  return col.apply(lambda x: m if(x<lower) | (x>upper) else x)
df[df.select_dtypes(include='number').columns]=df.select_dtypes(include='number').apply(replaceNoisy)

In [64]:
df

      A  B
0   1.0  a
1   2.0  b
2   3.0  c
3   3.0  c
4  10.0  e

In [65]:
d1=df.groupby('A')['B'].count()

In [66]:
d1

A
1.0     1
2.0     1
3.0     2
10.0    1
Name: B, dtype: int64

In [67]:
df=df.drop_duplicates()

In [68]:
df

      A  B
0   1.0  a
1   2.0  b
2   3.0  c
4  10.0  e

In [69]:
df=df.drop(columns='B')

In [70]:
df

      A
0   1.0
1   2.0
2   3.0
4  10.0

In [71]:
df['A']=df['A'].apply(pd.to_numeric)