In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df1=pd.read_excel('../Datasets/Northwind.xlsx',sheet_name='Products')
df2=pd.read_excel('../Datasets/Northwind.xlsx',sheet_name='Categories')
df3=pd.read_excel('../Datasets/Northwind.xlsx',sheet_name='Customers')
df4=pd.read_excel('../Datasets/Northwind.xlsx',sheet_name='Employees')
df5=pd.read_excel('../Datasets/Northwind.xlsx',sheet_name='Orders')
df6=pd.read_excel('../Datasets/Northwind.xlsx',sheet_name='Order Details')

In [4]:
df6.columns

Index(['OrderID', 'ProductID', 'UnitPrice', 'Quantity', 'Discount'], dtype='object')

In [5]:
df1.columns

Index(['ProductID', 'ProductName', 'SupplierID', 'CategoryID',
       'QuantityPerUnit', 'UnitPrice', 'UnitsInStock', 'UnitsOnOrder',
       'ReorderLevel', 'Discontinued'],
      dtype='object')

In [6]:
df7=df6.merge(df1,on='ProductID')

In [7]:
df7

,OrderID,ProductID,UnitPrice_x,Quantity,Discount,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice_y,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued
0,10248,11,14.00,12,0.00,Queso Cabrales,5,4,1 kg pkg.,21.00,22,30,30,False
1,10248,42,9.80,10,0.00,Singaporean Hokkien Fried Mee,20,5,32 - 1 kg pkgs.,14.00,26,0,0,True
2,10248,72,34.80,5,0.00,Mozzarella di Giovanni,14,4,24 - 200 g pkgs.,34.80,14,0,0,False
3,10249,14,18.60,9,0.00,Tofu,6,7,40 - 100 g pkgs.,23.25,35,0,0,False
4,10249,51,42.40,40,0.00,Manjimup Dried Apples,24,7,50 - 300 g pkgs.,53.00,20,0,10,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2150,11077,64,33.25,2,0.03,Wimmers gute Semmelknödel,12,5,20 bags x 4 pieces,33.25,22,80,30,False
2151,11077,66,17.00,1,0.00,Louisiana Hot Spiced Okra,2,2,24 - 8 oz jars,17.00,4,100,20,False
2152,11077,73,15.00,2,0.01,Röd Kaviar,17,8,24 - 150 g jars,15.00,101,0,5,False
2153,11077,75,7.75,4,0.00,Rhönbräu Klosterbier,12,1,24 - 0.5 l bottles,7.75,125,0,25,False
2154,11077,77,13.00,2,0.00,Original Frankfurter grüne Soße,12,2,12 boxes,13.00,32,0,15,False

In [8]:
df=df7.merge(df5,on='OrderID')

In [9]:
df

,OrderID,ProductID,UnitPrice_x,Quantity,Discount,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice_y,...,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,ShipCity,ShipRegion,ShipPostalCode,ShipCountry
0,10248,11,14.00,12,0.00,Queso Cabrales,5,4,1 kg pkg.,21.00,...,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
1,10248,42,9.80,10,0.00,Singaporean Hokkien Fried Mee,20,5,32 - 1 kg pkgs.,14.00,...,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
2,10248,72,34.80,5,0.00,Mozzarella di Giovanni,14,4,24 - 200 g pkgs.,34.80,...,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
3,10249,14,18.60,9,0.00,Tofu,6,7,40 - 100 g pkgs.,23.25,...,1996-08-16,1996-07-10,1,11.61,Toms Spezialitäten,Luisenstr. 48,Münster,NaN,44087,Germany
4,10249,51,42.40,40,0.00,Manjimup Dried Apples,24,7,50 - 300 g pkgs.,53.00,...,1996-08-16,1996-07-10,1,11.61,Toms Spezialitäten,Luisenstr. 48,Münster,NaN,44087,Germany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2150,11077,64,33.25,2,0.03,Wimmers gute Semmelknödel,12,5,20 bags x 4 pieces,33.25,...,1998-06-03,NaT,2,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,Albuquerque,NM,87110,USA
2151,11077,66,17.00,1,0.00,Louisiana Hot Spiced Okra,2,2,24 - 8 oz jars,17.00,...,1998-06-03,NaT,2,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,Albuquerque,NM,87110,USA
2152,11077,73,15.00,2,0.01,Röd Kaviar,17,8,24 - 150 g jars,15.00,...,1998-06-03,NaT,2,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,Albuquerque,NM,87110,USA
2153,11077,75,7.75,4,0.00,Rhönbräu Klosterbier,12,1,24 - 0.5 l bottles,7.75,...,1998-06-03,NaT,2,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,Albuquerque,NM,87110,USA
2154,11077,77,13.00,2,0.00,Original Frankfurter grüne Soße,12,2,12 boxes,13.00,...,1998-06-03,NaT,2,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,Albuquerque,NM,87110,USA

In [10]:
df.columns

Index(['OrderID', 'ProductID', 'UnitPrice_x', 'Quantity', 'Discount',
       'ProductName', 'SupplierID', 'CategoryID', 'QuantityPerUnit',
       'UnitPrice_y', 'UnitsInStock', 'UnitsOnOrder', 'ReorderLevel',
       'Discontinued', 'CustomerID', 'EmployeeID', 'OrderDate', 'RequiredDate',
       'ShippedDate', 'ShipVia', 'Freight', 'ShipName', 'ShipAddress',
       'ShipCity', 'ShipRegion', 'ShipPostalCode', 'ShipCountry'],
      dtype='object')

In [11]:
df=df.merge(df2,on="CategoryID")

In [ ]:
d1=df.groupby('Category')['S']

In [ ]:
combinedDf=pd.concat([df1,df2],axis=1)

In [ ]:
combinedDf.to_excel('combined.xlsx')